#!/bin/python3

import argparse as ap
import os
import random
from math import ceil

parser = ap.ArgumentParser(description='all to github')
parser.add_argument('-d','--dir',type=str,default='.',help='Choose directory for push')
args = parser.parse_args()
d = args.dir

now = os.getcwd()

hi = os.popen(f'find {d} -maxdepth 4 | grep "\.git"')

git_dir = {now+'/' + i.split('.git')[0] for i in list(hi.readlines())}

print('Push list!\n',*git_dir, sep='\n  ', end='\n\n\n')
print('Start!')
while git_dir:
    di = git_dir.pop()
    os.system(f'echo "" && cd {di} && pwd && git add .')
    hi = os.popen(f'cd {di} && git status')
    os.system(f'cd {di} && git reset HEAD')
    addlist = [eval(f"""b'{i.split(":")[-1].strip()}'""").decode('utf-8') for i in list(hi.readlines())[2:] if ':' in i and not i.strip().endswith(':')]
    answer = 'y'
    push = False

    if not addlist: print('  nothing to commit.')
    else: 
        print('  Addlist:',end='')
        print('  ',*addlist, sep='\n  ',end='\n\n')
        answer = input(f"    repository name: {di.split('/')[-2].ljust(30,' ')}\n    -> start commit? (y/n): ")

    while (answer=='y' or answer=='Y') and addlist:
        for i, j in enumerate(addlist):
            print(' '*10,j.ljust(50,' '),'- ',str(i),'\n')
        randnum = list(map(str,{random.randint(0,len(addlist)-1) for i in range(ceil(len(addlist)/2))}))
        checklist = input(f'\n    Enter number list(ex: {" ".join(randnum)} or, "all"): ').split()
        commit = input('\n    commit message: ')
        
        if 'all' in checklist:
            os.system(f'cd {di} && git add .')
            os.system(f'cd {di} && git commit -m "{commit}"')
            push = True
            break
        else:
            checklist = list(map(int, checklist))
            for i in sorted(checklist,reverse=True):
                contents = addlist.pop(i)
                contents = contents if ' -> ' not in contents else contents.split(' -> ')[-1]
                print(f'git add {contents}')
                os.system(f'cd {di} && git add {contents}')
        os.system(f'cd {di} && git commit -m "{commit}"')
        push = True

        if addlist:
            answer = input(f"    repository name: {di.split('/')[-2].ljust(30,' ')}\n     -> continue? (y/n): ")

    if push:
        branch = input('\n    branch name: ')
        os.system(f'cd {di} && git push origin {branch}')

os.system('clear -x')
print('  All is done.')
